import { ClientProviders } from "@/components/ClientProviders";
import StyledComponentsRegistry from "@/lib/registry";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>GoodBoy Foundation</title>
        <meta name="Goodboy Foundation" content="Generated by create next app" />
      </head>
      <body
      >
        <StyledComponentsRegistry>
          <ClientProviders>
            {children}
          </ClientProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
